name = "DLPipelines"
uuid = "e6530d7c-7faa-4ede-a0d6-9eff9baad396"
authors = ["Lorenz Ohly <lorenz.ohly@gmail.com> and contributors"]
version = "0.2.0"

[deps]
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataLoaders = "0.1"
LearnBase = "0.3, 0.4"
MLDataPattern = "0.5"
Parameters = "0.12"
julia = "1"

[publish]
theme = "theme"
title = "DLPipelines.jl"
